### ISSUE TITLE
CircleCI build is failing

### ISSUE THREAD

**Issue by kenichi-fukushima** [infostellarinc/starcoder#151]
This is different from https://github.com/infostellarinc/starcoder/issues/148

Builds on CircleCI fail with this error message.
```
Received 'killed' signal
```

This is what all we know about the failure at the moment.

**Comment by reiinakano** [comment]
I've seen this a bunch of times when the build times out. The only solution is to make the build system faster by upgrading our subscription or just jeep rebuilding until it eventually works :(

**Comment by kenichi-fukushima** [comment]
Timeout could a reason.

But the latest run failed for another reason.

https://circleci.com/gh/infostellarinc/starcoder/626?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

There are a lot of messages like this.
```
go: go.uber.org/atomic@v1.3.2: unrecognized import path "go.uber.org/atomic" (https fetch: Get https://go.uber.org/atomic?go-get=1: x509: certificate signed by unknown authority)
```

Perhaps a CA certificate in the base image used for build has expired?

**Comment by kenichi-fukushima** [comment]
Succeeded in reproducing the certificate issue locally and confirmed it went away after running
```
# apt-get install ca-certificates
```

**Comment by kenichi-fukushima** [comment]
Reported to curiostack.
https://github.com/curioswitch/curiostack/issues/322
